create table yp_dm.dm_sku_temp as
(select coalesce(new.sku_id, old.sku_id)                                             sku_id,
       coalesce(new.order_last_30d_count, 0)                                           order_last_30d_count,
       coalesce(new.order_last_30d_num, 0)                                             order_last_30d_num,
       coalesce(new.order_last_30d_amount, 0)                                          order_last_30d_amount,
       coalesce(old.order_count, 0) + coalesce(new.order_count, 0)                     order_count,
       coalesce(old.order_num, 0) + coalesce(new.order_num, 0)                         order_num,
       coalesce(old.order_amount, 0) + coalesce(new.order_amount, 0)                   order_amount,
       coalesce(new.payment_last_30d_count, 0)                                         payment_last_30d_count,
       coalesce(new.payment_last_30d_num, 0)                                           payment_last_30d_num,
       coalesce(new.payment_last_30d_amount, 0)                                        payment_last_30d_amount,
       coalesce(old.payment_count, 0) + coalesce(new.payment_count, 0)                 payment_count,
       coalesce(old.payment_num, 0) + coalesce(new.payment_num, 0)                     payment_num,
       coalesce(old.payment_amount, 0) + coalesce(new.payment_amount, 0)               payment_amount,
       coalesce(new.refund_last_30d_count, 0)                                          refund_last_30d_count,
       coalesce(new.refund_last_30d_num, 0)                                            refund_last_30d_num,
       coalesce(new.refund_last_30d_amount, 0)                                         refund_last_30d_amount,
       coalesce(old.refund_count, 0) + coalesce(new.refund_count, 0)                   refund_count,
       coalesce(old.refund_num, 0) + coalesce(new.refund_num, 0)                       refund_num,
       coalesce(old.refund_amount, 0) + coalesce(new.refund_amount, 0)                 refund_amount,
       coalesce(new.cart_last_30d_count, 0)                                            cart_last_30d_count,
       coalesce(new.cart_last_30d_num, 0)                                              cart_last_30d_num,
       coalesce(old.cart_count, 0) + coalesce(new.cart_count, 0)                       cart_count,
       coalesce(old.cart_num, 0) + coalesce(new.cart_num, 0)                           cart_num,
       coalesce(new.favor_last_30d_count, 0)                                           favor_last_30d_count,
       coalesce(old.favor_count, 0) + coalesce(new.favor_count, 0)                     favor_count,
       coalesce(new.evaluation_last_30d_good_count, 0)                                 evaluation_last_30d_good_count,
       coalesce(new.evaluation_last_30d_mid_count, 0)                                  evaluation_last_30d_mid_count,
       coalesce(new.evaluation_last_30d_bad_count, 0)                                  evaluation_last_30d_bad_count,
       coalesce(old.evaluation_good_count, 0) + coalesce(new.evaluation_good_count, 0) evaluation_good_count,
       coalesce(old.evaluation_mid_count, 0) + coalesce(new.evaluation_mid_count, 0)   evaluation_mid_count,
       coalesce(old.evaluation_bad_count, 0) + coalesce(new.evaluation_bad_count, 0)   evaluation_bad_count
from (select sku_id,
             sum(order_count)                                     order_last_30d_count,
             sum(order_num)                                       order_last_30d_num,
             sum(order_amount)                                    order_last_30d_amount,
             sum(if(dt = '2020-05-09', order_count, 0))           order_count,
             sum(if(dt = '2020-05-09', order_num, 0))             order_num,
             sum(if(dt = '2020-05-09', order_amount, 0))          order_amount,
             sum(payment_count)                                   payment_last_30d_count,
             sum(payment_num)                                     payment_last_30d_num,
             sum(payment_amount)                                  payment_last_30d_amount,
             sum(if(dt = '2020-05-09', payment_count, 0))         payment_count,
             sum(if(dt = '2020-05-09', payment_num, 0))           payment_num,
             sum(if(dt = '2020-05-09', payment_amount, 0))        payment_amount,
             sum(refund_count)                                    refund_last_30d_count,
             sum(refund_num)                                      refund_last_30d_num,
             sum(refund_amount)                                   refund_last_30d_amount,
             sum(if(dt = '2020-05-09', refund_count, 0))          refund_count,
             sum(if(dt = '2020-05-09', refund_num, 0))            refund_num,
             sum(if(dt = '2020-05-09', refund_amount, 0))         refund_amount,
             sum(cart_count)                                      cart_last_30d_count,
             sum(cart_num)                                        cart_last_30d_num,
             sum(if(dt = '2020-05-09', cart_count, 0))            cart_count,
             sum(if(dt = '2020-05-09', cart_num, 0))              cart_num,
             sum(favor_count)                                     favor_last_30d_count,
             sum(if(dt = '2020-05-09', favor_count, 0))           favor_count,
             sum(evaluation_good_count)                           evaluation_last_30d_good_count,
             sum(evaluation_mid_count)                            evaluation_last_30d_mid_count,
             sum(evaluation_bad_count)                            evaluation_last_30d_bad_count,
             sum(if(dt = '2020-05-09', evaluation_good_count, 0)) evaluation_good_count,
             sum(if(dt = '2020-05-09', evaluation_mid_count, 0))  evaluation_mid_count,
             sum(if(dt = '2020-05-09', evaluation_bad_count, 0))  evaluation_bad_count
      from yp_dws.dws_sku_daycount
      where dt >= cast(date_add('day', -30, date '2020-05-09') as varchar)
      group by sku_id) new
         full join
     (select sku_id,
             order_last_30d_count,
             order_last_30d_num,
             order_last_30d_amount,
             order_count,
             order_num,
             order_amount,
             payment_last_30d_count,
             payment_last_30d_num,
             payment_last_30d_amount,
             payment_count,
             payment_num,
             payment_amount,
             refund_last_30d_count,
             refund_last_30d_num,
             refund_last_30d_amount,
             refund_count,
             refund_num,
             refund_amount,
             cart_last_30d_count,
             cart_last_30d_num,
             cart_count,
             cart_num,
             favor_last_30d_count,
             favor_count,
             evaluation_last_30d_good_count,
             evaluation_last_30d_mid_count,
             evaluation_last_30d_bad_count,
             evaluation_good_count,
             evaluation_mid_count,
             evaluation_bad_count
      from yp_dm.dm_sku
     ) old
     on new.sku_id = old.sku_id)
;

delete from yp_dm.dm_sku;
insert into yp_dm.dm_sku
select * from yp_dm.dm_sku_temp;